### ISSUE TITLE
Add method parameters to exception stack trace

### ISSUE THREAD

**Issue by murkaje** [murkaje/npe-blame-agent#7]
Usually the interesting location is a few frames before the exception and as some functions are pure, parameters/fields with specific values can help reproduce errors if some specific inputs were not considered in tests.

Consider

```java
public class SomeObject {
  public String maybeNullName;
  @Override public String toString() { return "SomeObject { name: " + maybeNullName + " }"; }
}

...

public String foo(SomeObject obj) {
  return bar(obj.maybeNullName);
}

public String bar(String name) {
  return name.toLowerCase();
}
```

The resulting stack trace is

```
java.lang.NullPointerException: Invoking java.lang.String#toLowerCase on null method parameter name:java.lang.String
	at com.Foo.bar(Foo.java:99)
	at com.Foo.foo(Foo.java:77)
	...
```

This can be improved, for example:

```
java.lang.NullPointerException: Invoking java.lang.String#toLowerCase on null method parameter name:java.lang.String
	at com.Foo.bar(Foo.java:99) [ name = null ]
	at com.Foo.foo(Foo.java:77) [ obj = 'SomeObject { name: null }' ]
	...
```

Few things to consider:
* Using toString can lead to a lot of bloat in the middle of stack traces.
   * Print identity hashcode if string is long?
   * Fancy heuristics to limit printing only of relevant parameters
* Calling toString can fail if object is a proxy, its InvocationHandler checks for something, e.g. whether it's being called in the correct thread that has some ThreadLocal set, e.g. Spring request/session scoped beans.
* Parameter names may be in [MethodParameters attribute](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.24), [LocalVariableTable attribute](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.13), both or neither
   * Use parameter index and type when info not present?
* There's useful info also in fields and local variables(value can be queried if they are still in scope as defined by the range in LocalVariableTable)
   * Printing too much?

**Comment by murkaje** [comment]
Still on hold while trying to figure out how much information to print an when. Right now can get primitive values and identity toString when setting -agentpath:.../libnpeblame.so=trace

Possibly tie it to NPE tracing analysis and print out relevant info. E.g. getter/field of some object returned null, print that object's toString. If field belongs to _this_ object, print _this_ toString.
